### ISSUE TITLE
missing type declaration issue

### ISSUE THREAD

**Issue by milindgoel15** [vpodk/react-hamburger-drawer#360]
Tried installing the package in nextjs v14 and when importing the burger, it throws error as

```console
Could not find a declaration file for module 'react-hamburger-drawer'. 'd:/Programming/Web Projects/shubh-portfolio/node_modules/react-hamburger-drawer/dist/index.js' implicitly has an 'any' type.
  There are types at 'project/node_modules/react-hamburger-drawer/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-hamburger-drawer' library may need to update its package.json or typings.
```

**Comment by vpodk** [comment]
Thank you for raising this issue. The [index.d.ts](https://github.com/Datamart/react-hamburger-drawer/blob/main/index.d.ts) file has been updated and a new package has been published ([v21.11.26](https://www.npmjs.com/package/react-hamburger-drawer)). Also check out the section for [SSRs (Next.js 13+)](https://github.com/Datamart/react-hamburger-drawer/tree/main?tab=readme-ov-file#nextjs-v13-and-other-ssrs) in the README. Let me know if you have any questions.
